#-*- mode: python -*-
# -*- coding: utf-8 -*-

from pynput.keyboard import Key, Controller

from datetime import datetime
import pytz
import pymsgbox
import sys
import os
import time
import pyautogui as pg

pymsgbox.rootWindowPosition = "+0+0"

keyboard = Controller()

def num1():
    keyboard.press("1")
    time.sleep(0.01)
    keyboard.release("1")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num2():
    keyboard.press("2")
    time.sleep(0.01)
    keyboard.release("2")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num3():
    keyboard.press("3")
    time.sleep(0.01)
    keyboard.release("3")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num4():
    keyboard.press("4")
    time.sleep(0.01)
    keyboard.release("4")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num5():
    keyboard.press("5")
    time.sleep(0.01)
    keyboard.release("5")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num6():
    keyboard.press("6")
    time.sleep(0.01)
    keyboard.release("6")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num7():
    keyboard.press("7")
    time.sleep(0.01)
    keyboard.release("7")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num8():
    keyboard.press("8")
    time.sleep(0.01)
    keyboard.release("8")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num9():
    keyboard.press("9")
    time.sleep(0.01)
    keyboard.release("9")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num0():
    keyboard.press("0")
    time.sleep(0.01)
    keyboard.release("0")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num10():
    keyboard.press("1")
    time.sleep(0.01)
    keyboard.release("1")
    time.sleep(0.01)
    keyboard.press("0")
    keyboard.release("0")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)   
    time.sleep(0.01)

def num11():
    keyboard.press("1")
    time.sleep(0.01)
    keyboard.release("1")
    time.sleep(0.01)
    keyboard.press("1")
    time.sleep(0.01)
    keyboard.release("1")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)   
    time.sleep(0.01)

def num12():
    keyboard.press("1")
    time.sleep(0.01)
    keyboard.release("1")
    time.sleep(0.01)
    keyboard.press("2")
    time.sleep(0.01)
    keyboard.release("2")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)   
    time.sleep(0.01)

def num13():
    keyboard.press("1")
    time.sleep(0.01)
    keyboard.release("1")
    time.sleep(0.01)
    keyboard.press("3")
    time.sleep(0.01)
    keyboard.release("3")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num14():
    keyboard.press("1")
    time.sleep(0.01)
    keyboard.release("1")
    time.sleep(0.01)
    keyboard.press("4")
    time.sleep(0.01)
    keyboard.release("4")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num15():
    keyboard.press("1")
    time.sleep(0.01)
    keyboard.release("1")
    time.sleep(0.01)
    keyboard.press("5")
    time.sleep(0.01)
    keyboard.release("5")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num16():
    keyboard.press("1")
    time.sleep(0.01)
    keyboard.release("1")
    time.sleep(0.01)
    keyboard.press("6")
    time.sleep(0.01)
    keyboard.release("6")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num17():
    keyboard.press("1")
    time.sleep(0.01)
    keyboard.release("1")
    time.sleep(0.01)
    keyboard.press("7")
    time.sleep(0.01)
    keyboard.release("7")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num18():
    keyboard.press("1")
    time.sleep(0.01)
    keyboard.release("1")
    time.sleep(0.01)
    keyboard.press("8")
    time.sleep(0.01)
    keyboard.release("8")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num19():
    keyboard.press("1")
    time.sleep(0.01)
    keyboard.release("1")
    time.sleep(0.01)
    keyboard.press("9")
    time.sleep(0.01)
    keyboard.release("9")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num20():
    keyboard.press("2")
    time.sleep(0.01)
    keyboard.release("2")
    time.sleep(0.01)
    keyboard.press("0")
    time.sleep(0.01)
    keyboard.release("0")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num21():
    keyboard.press("2")
    time.sleep(0.01)
    keyboard.release("2")
    time.sleep(0.01)
    keyboard.press("1")
    time.sleep(0.01)
    keyboard.release("1")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num22():
    keyboard.press("2")
    time.sleep(0.01)
    keyboard.release("2")
    time.sleep(0.01)
    keyboard.press("2")
    time.sleep(0.01)
    keyboard.release("2")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num23():
    keyboard.press("2")
    time.sleep(0.01)
    keyboard.release("2")
    time.sleep(0.01)
    keyboard.press("3")
    time.sleep(0.01)
    keyboard.release("3")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num24():
    keyboard.press("2")
    time.sleep(0.01)
    keyboard.release("2")
    time.sleep(0.01)
    keyboard.press("4")
    time.sleep(0.01)
    keyboard.release("4")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num25():
    keyboard.press("2")
    time.sleep(0.01)
    keyboard.release("2")
    time.sleep(0.01)
    keyboard.press("5")
    time.sleep(0.01)
    keyboard.release("5")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num26():
    keyboard.press("2")
    time.sleep(0.01)
    keyboard.release("2")
    time.sleep(0.01)
    keyboard.press("6")
    time.sleep(0.01)
    keyboard.release("6")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num27():
    keyboard.press("2")
    time.sleep(0.01)
    keyboard.release("2")
    time.sleep(0.01)
    keyboard.press("7")
    time.sleep(0.01)
    keyboard.release("7")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num28():
    keyboard.press("2")
    time.sleep(0.01)
    keyboard.release("2")
    time.sleep(0.01)
    keyboard.press("8")
    time.sleep(0.01)
    keyboard.release("8")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num29():
    keyboard.press("2")
    time.sleep(0.01)
    keyboard.release("2")
    time.sleep(0.01)
    keyboard.press("9")
    time.sleep(0.01)
    keyboard.release("9")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num30():
    keyboard.press("3")
    time.sleep(0.01)
    keyboard.release("3")
    time.sleep(0.01)
    keyboard.press("0")
    time.sleep(0.01)
    keyboard.release("0")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num31():
    keyboard.press("3")
    time.sleep(0.01)
    keyboard.release("3")
    time.sleep(0.01)
    keyboard.press("1")
    time.sleep(0.01)
    keyboard.release("1")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num32():
    keyboard.press("3")
    time.sleep(0.01)
    keyboard.release("3")
    time.sleep(0.01)
    keyboard.press("2")
    time.sleep(0.01)
    keyboard.release("2")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num33():
    keyboard.press("3")
    time.sleep(0.01)
    keyboard.release("3")
    time.sleep(0.01)
    keyboard.press("3")
    time.sleep(0.01)
    keyboard.release("3")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num34():
    keyboard.press("3")
    time.sleep(0.01)
    keyboard.release("3")
    time.sleep(0.01)
    keyboard.press("4")
    time.sleep(0.01)
    keyboard.release("4")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num35():
    keyboard.press("3")
    time.sleep(0.01)
    keyboard.release("3")
    time.sleep(0.01)
    keyboard.press("5")
    time.sleep(0.01)
    keyboard.release("5")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num36():
    keyboard.press("3")
    time.sleep(0.01)
    keyboard.release("3")
    time.sleep(0.01)
    keyboard.press("6")
    time.sleep(0.01)
    keyboard.release("6")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num37():
    keyboard.press("3")
    time.sleep(0.01)
    keyboard.release("3")
    time.sleep(0.01)
    keyboard.press("7")
    time.sleep(0.01)
    keyboard.release("7")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num38():
    keyboard.press("3")
    time.sleep(0.01)
    keyboard.release("3")
    time.sleep(0.01)
    keyboard.press("8")
    time.sleep(0.01)
    keyboard.release("8")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num39():
    keyboard.press("3")
    time.sleep(0.01)
    keyboard.release("3")
    time.sleep(0.01)
    keyboard.press("9")
    time.sleep(0.01)
    keyboard.release("9")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num40():
    keyboard.press("4")
    time.sleep(0.01)
    keyboard.release("4")
    time.sleep(0.01)
    keyboard.press("0")
    time.sleep(0.01)
    keyboard.release("0")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num41():
    keyboard.press("4")
    time.sleep(0.01)
    keyboard.release("4")
    time.sleep(0.01)
    keyboard.press("1")
    time.sleep(0.01)
    keyboard.release("1")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter) 
    time.sleep(0.01)

def num42():
    keyboard.press("4")
    time.sleep(0.01)
    keyboard.release("4")
    time.sleep(0.01)
    keyboard.press("2")
    time.sleep(0.01)
    keyboard.release("2")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)   
    time.sleep(0.01)

def num43():
    keyboard.press("4")
    time.sleep(0.01)
    keyboard.release("4")
    time.sleep(0.01)
    keyboard.press("3")
    time.sleep(0.01)
    keyboard.release("3")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num44():
    keyboard.press("4")
    time.sleep(0.01)
    keyboard.release("4")
    time.sleep(0.01)
    keyboard.press("4")
    time.sleep(0.01)
    keyboard.release("4")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num45():
    keyboard.press("4")
    time.sleep(0.01)
    keyboard.release("4")
    time.sleep(0.01)
    keyboard.press("5")
    time.sleep(0.01)
    keyboard.release("5")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num46():
    keyboard.press("4")
    time.sleep(0.01)
    keyboard.release("4")
    time.sleep(0.01)
    keyboard.press("6")
    time.sleep(0.01)
    keyboard.release("6")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num47():
    keyboard.press("4")
    time.sleep(0.01)
    keyboard.release("4")
    time.sleep(0.01)
    keyboard.press("7")
    time.sleep(0.01)
    keyboard.release("7")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num48():
    keyboard.press("4")
    time.sleep(0.01)
    keyboard.release("4")
    time.sleep(0.01)
    keyboard.press("8")
    time.sleep(0.01)
    keyboard.release("8")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)  
    time.sleep(0.01)

def num49():
    keyboard.press("4")
    time.sleep(0.01)
    keyboard.release("4")
    time.sleep(0.01)
    keyboard.press("9")
    time.sleep(0.01)
    keyboard.release("9")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter) 
    time.sleep(0.01)

def num50():
    keyboard.press("5")
    time.sleep(0.01)
    keyboard.release("5")
    time.sleep(0.01)
    keyboard.press("0")
    time.sleep(0.01)
    keyboard.release("0")
    time.sleep(0.01)
    keyboard.press(Key.enter)
    time.sleep(0.01)
    keyboard.release(Key.enter)   
    time.sleep(0.01)

def enter():
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)   

def restart():
    print("argv was",sys.argv)
    print("sys.executable was", sys.executable)
    print("restart now")

    os.execv(sys.executable, ['python'] + sys.argv)

# ----------------------------------------------- 

def number():
    #facebook ส่งก่อน 3 ตัว เวลา 00:00:59
    for i in range(1):
        num14()
        num14()
        num15()
        for i in range(int(start),int(stop) + 1, int(1)):
            method = eval("num"+str(i))
            method()

    conf = pg.confirm('ส่งข้อความสำเร็จ! \nคุณต้องการเริ่มโปรแกรมใหม่ใช่หรือไม่ ?',buttons=['เริ่มใหม่','ยกเลิก'])
    restart() if conf == 'เริ่มใหม่' else exit()

def setRange():
    for i in range(10):
        keyboard.press("1")
        time.sleep(0.01)
        keyboard.release("1")
        time.sleep(0.01)
        keyboard.press("0")
        time.sleep(0.01)
        keyboard.release("0")
        time.sleep(0.01)
        keyboard.press("-")
        time.sleep(0.01)
        keyboard.release("-")
        time.sleep(0.01)
        keyboard.press("3")
        time.sleep(0.01)
        keyboard.release("3")
        time.sleep(0.01)
        keyboard.press("9")
        time.sleep(0.01)
        keyboard.release("9")
        time.sleep(0.01)
        keyboard.press(Key.enter)
        time.sleep(0.01)
        keyboard.release(Key.enter)   
        time.sleep(0.01)

    conf = pg.confirm('ส่งข้อความสำเร็จ! \nคุณต้องการเริ่มโปรแกรมใหม่ใช่หรือไม่ ?',buttons=['เริ่มใหม่','ยกเลิก'])
    restart() if conf == 'เริ่มใหม่' else exit()

start = pg.prompt("มือที่ต้องการจองเริ่ม", "Bot Message", "")
stop = pg.prompt("มือที่ต้องการจองสิ้นสุด", "Bot Message", "")

btn = pg.confirm(text='กดปุ่ม ส่ง เพื่อเริ่มทำงาน', title='Bot Message', buttons=['ส่ง','กำหนดเวลา','ส่งแบบหลายมือ','ยกเลิก'])

if btn == 'ส่ง':
    number()
elif btn == 'กำหนดเวลา':
    timeSet = pg.prompt(text='กำหนดเวลาในการส่งข้อความ ตัวอย่าง 21:00:59', title='กำหนดเวลา' , default='')
    while True:
        tz_Bangkok = pytz.timezone('Asia/Bangkok')
        datetime_Bangkok = datetime.now(tz_Bangkok)
        # print("Bangkok time:", datetime_Bangkok.strftime("%H:%M:%S"))
        if datetime_Bangkok.strftime("%H:%M:%S") == timeSet:
            number()
elif btn == 'ส่งแบบหลายมือ':
    timeSet = pg.prompt(text='กำหนดเวลาในการส่งข้อความ ตัวอย่าง 21:00:59', title='กำหนดเวลา' , default='')
    while True:
        tz_Bangkok = pytz.timezone('Asia/Bangkok')
        datetime_Bangkok = datetime.now(tz_Bangkok)
        # print("Bangkok time:", datetime_Bangkok.strftime("%H:%M:%S"))
        if datetime_Bangkok.strftime("%H:%M:%S") == timeSet:
            setRange()
else:
    exit()